from orchestrator.interfaces.mcp.server import create_plan

workspace = r"d:\datos jt7\proyectos\agentes_autonomos\trade bot\bot-trader-orquestado"

tasks = [
    {
        "prompt": "Audita bot-trader-orquestado sin modificar codigo. Revisa estrategia, backtest, risk manager, modelos y datos. Crea docs/MARKET_ADAPTIVE_AUDIT.md con riesgos, deuda tecnica y un plan priorizado. No afirmes rentabilidad.",
        "executor": "kilo",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\docs\MARKET_ADAPTIVE_AUDIT.md"],
        "validation_commands": [["python", "-c", "from pathlib import Path; p=Path('docs/MARKET_ADAPTIVE_AUDIT.md'); assert p.exists() and p.stat().st_size > 500"]],
        "timeout_seconds": 180,
        "max_retries": 1,
        "approval_policy": "auto_on_pass",
    },
    {
        "prompt": "Implementa solo un detector de regimen de mercado en src/bot_trader_orquestado/market_regime.py. Debe clasificar tendencia, rango y volatilidad usando exclusivamente velas disponibles hasta t, sin lookahead. Añade tipos y funciones pequeñas; no cambies backtest ni estrategia.",
        "executor": "kilo",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\src\bot_trader_orquestado\market_regime.py"],
        "validation_commands": [["python", "-m", "py_compile", "src/bot_trader_orquestado/market_regime.py"]],
        "depends_on": [0],
        "timeout_seconds": 240,
        "max_retries": 1,
        "approval_policy": "auto_on_pass",
    },
    {
        "prompt": "Crea únicamente tests/test_market_regime.py para el detector de regimen. Comprueba orden temporal, ausencia de lookahead, datos insuficientes y clasificaciones deterministas. Ejecuta pytest de ese archivo.",
        "executor": "cline",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\tests\test_market_regime.py"],
        "validation_commands": [["python", "-m", "pytest", "tests/test_market_regime.py", "-q"]],
        "depends_on": [1],
        "timeout_seconds": 180,
        "max_retries": 1,
        "approval_policy": "auto_on_pass",
    },
    {
        "prompt": "Implementa solo un risk manager adaptativo en src/bot_trader_orquestado/adaptive_risk.py. Debe limitar riesgo por operacion, riesgo diario, perdida consecutiva, volatilidad y drawdown; reducir exposicion en volatilidad alta; nunca aumentar riesgo para recuperar perdidas. Añade trailing stop dinamico basado en ATR con distancia minima. No habilites live trading.",
        "executor": "kilo",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\src\bot_trader_orquestado\adaptive_risk.py"],
        "validation_commands": [["python", "-m", "py_compile", "src/bot_trader_orquestado/adaptive_risk.py"]],
        "depends_on": [2],
        "timeout_seconds": 300,
        "max_retries": 1,
        "approval_policy": "auto_on_pass",
        "tags": ["risk", "milestone"],
    },
    {
        "prompt": "Crea únicamente tests/test_adaptive_risk.py. Prueba caps de riesgo, kill switch de drawdown, perdida diaria, perdidas consecutivas y trailing stop ATR que solo avanza a favor. Ejecuta pytest del archivo.",
        "executor": "cline",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\tests\test_adaptive_risk.py"],
        "validation_commands": [["python", "-m", "pytest", "tests/test_adaptive_risk.py", "-q"]],
        "depends_on": [3],
        "timeout_seconds": 180,
        "max_retries": 1,
        "approval_policy": "auto_on_pass",
    },
    {
        "prompt": "Integra market_regime y adaptive_risk en el backtest existente sin habilitar live trading. Incluye comision, spread, slippage, sizing, stop loss y trailing stop. Modifica solo los archivos necesarios y actualiza tests. Ejecuta la suite completa.",
        "executor": "kilo",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\src\**", workspace + r"\tests\**", workspace + r"\docs\**"],
        "validation_commands": [["python", "-m", "pytest", "-q"]],
        "depends_on": [4],
        "timeout_seconds": 300,
        "max_retries": 1,
        "approval_policy": "manual",
        "tags": ["milestone", "backtest"],
    },
    {
        "prompt": "Ejecuta un backtest reproducible con datos historicos reales documentados, separacion temporal train/validation/test, comision, spread y slippage. Genera reports/adaptive_risk_backtest.json con data_is_real, data_source, costs_included, out_of_sample, total_return, max_drawdown, sharpe, profit_factor, total_trades y parametros. Si no cumple objetivos, registra FAIL y no optimices sobre el test.",
        "executor": "cline",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\reports\adaptive_risk_backtest.json"],
        "validation_commands": [["python", "-c", "import json; from pathlib import Path; p=Path('reports/adaptive_risk_backtest.json'); d=json.loads(p.read_text()); required={'data_is_real','data_source','costs_included','out_of_sample','total_return','max_drawdown'}; assert required <= d.keys(); assert d['data_is_real'] is True"]],
        "depends_on": [5],
        "timeout_seconds": 300,
        "max_retries": 1,
        "approval_policy": "manual",
        "tags": ["milestone", "financial-evidence"],
    },
    {
        "prompt": "Revisa reports/adaptive_risk_backtest.json y el diff del proyecto. Comprueba leakage, costes, robustez, drawdown y que el trailing stop no introduce lookahead. Crea docs/ADAPTIVE_RISK_REVIEW.md con PASS/FAIL, riesgos residuales y recomendacion. Nunca declares garantizada la rentabilidad.",
        "executor": "cline",
        "workspace": workspace,
        "allowed_paths": [workspace + r"\docs\ADAPTIVE_RISK_REVIEW.md"],
        "validation_commands": [["python", "-c", "from pathlib import Path; p=Path('docs/ADAPTIVE_RISK_REVIEW.md'); assert p.exists() and p.stat().st_size > 300"]],
        "depends_on": [6],
        "timeout_seconds": 240,
        "max_retries": 1,
        "approval_policy": "manual",
        "tags": ["milestone", "review"],
    },
]

result = create_plan(
    "Bot adaptativo: riesgo conservador, regimenes de mercado y trailing stop dinamico",
    tasks,
    workspace=workspace,
    auto_execute=False,
    target_return=0.55,
    max_drawdown=0.20,
    max_iterations=5,
)
print(result)
